//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.14 at 10:35:52 PM COT 
//


package osb.rest.json.comprar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComprarServiceResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComprarServiceResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="comprarRS" type="{http://www.portobella.com/onlineStore/services/Comprar}ComprarRSType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComprarServiceResponseType", propOrder = {
    "comprarRS"
})
public class ComprarServiceResponseType {

    @XmlElement(required = true)
    protected ComprarRSType comprarRS;

    /**
     * Gets the value of the comprarRS property.
     * 
     * @return
     *     possible object is
     *     {@link ComprarRSType }
     *     
     */
    public ComprarRSType getComprarRS() {
        return comprarRS;
    }

    /**
     * Sets the value of the comprarRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComprarRSType }
     *     
     */
    public void setComprarRS(ComprarRSType value) {
        this.comprarRS = value;
    }

}
