//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.14 at 10:35:52 PM COT 
//


package osb.rest.json.comprar;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the osb.rest.json.comprar package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ComprarServiceRequest_QNAME = new QName("http://www.portobella.com/onlineStore/services/Comprar", "ComprarServiceRequest");
    private final static QName _ComprarServiceResponse_QNAME = new QName("http://www.portobella.com/onlineStore/services/Comprar", "ComprarServiceResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: osb.rest.json.comprar
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComprarServiceResponseType }
     * 
     */
    public ComprarServiceResponseType createComprarServiceResponseType() {
        return new ComprarServiceResponseType();
    }

    /**
     * Create an instance of {@link ComprarServiceRequestType }
     * 
     */
    public ComprarServiceRequestType createComprarServiceRequestType() {
        return new ComprarServiceRequestType();
    }

    /**
     * Create an instance of {@link ComprarRQType }
     * 
     */
    public ComprarRQType createComprarRQType() {
        return new ComprarRQType();
    }

    /**
     * Create an instance of {@link ComprarRSType }
     * 
     */
    public ComprarRSType createComprarRSType() {
        return new ComprarRSType();
    }

    /**
     * Create an instance of {@link TipoRopaType }
     * 
     */
    public TipoRopaType createTipoRopaType() {
        return new TipoRopaType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComprarServiceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portobella.com/onlineStore/services/Comprar", name = "ComprarServiceRequest")
    public JAXBElement<ComprarServiceRequestType> createComprarServiceRequest(ComprarServiceRequestType value) {
        return new JAXBElement<ComprarServiceRequestType>(_ComprarServiceRequest_QNAME, ComprarServiceRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComprarServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portobella.com/onlineStore/services/Comprar", name = "ComprarServiceResponse")
    public JAXBElement<ComprarServiceResponseType> createComprarServiceResponse(ComprarServiceResponseType value) {
        return new JAXBElement<ComprarServiceResponseType>(_ComprarServiceResponse_QNAME, ComprarServiceResponseType.class, null, value);
    }

}
